name: Makefile CI

on:
  push:
    branches: 
    - 'master'
  pull_request:
    branches:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image: image_test
      options: --privileged --ulimit core=-1 --security-opt seccomp=unconfined

    steps:
    - uses: actions/checkout@v2
      
    - name: Check astyle
      run: make check_format
