name: Makefile CI

on:
  push:
    branches: 
    - 'master'
  pull_request:
    branches:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Check astyle
      run: make check_format
